name: mahallda_app
description: A new Flutter project.
#publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  firebase_auth: ^5.6.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.11
  provider: ^6.1.5
  image_picker: ^1.1.2
  firebase_storage: ^12.4.9
  flutter_localizations: # Re-added for Flutter's built-in widget localization
    sdk: flutter
  firebase_core: ^3.15.1
  http: ^1.4.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  intl_phone_field: ^3.2.0
  flutter_gen: ^5.11.0
  flutter_gen_runner: ^5.11.0
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.1
  #collection: ^1.19.1
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  maths: ^0.0.2
  rxdart: ^0.28.0
  in_app_purchase: ^3.2.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/google_logo.png # Make sure this path is correct
    - assets/avatar_male.png
    - assets/avatar_female.png
    - assets/
    - l10n/
  #  - images/a_dot_ham.jpeg
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
#flutter_gen:
#  output: lib/gen/ # Generatsiya qilingan fayllar joylashuvi (ixtiyoriy)
 # integrations:
  #  flutter_svg: true # Agar SVG ishlatayotgan bo'lsangiz
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
