// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyCYfjWpGzcI-jE_XBgz9yK764fEp0M3hio',
      authDomain: 'mahallada-app.firebaseapp.com',
      projectId: 'mahallada-app',
      storageBucket: 'mahallada-app.firebasestorage.app',
      messagingSenderId: '415922539355',
      appId: '1:415922539355:web:d9ba9bdb406f3f08b5a87e',
      measurementId: 'G-X9T6QGDDF9');

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyCgdXhY-KYsj_qudluF-eJ136zyBlzLoQs',
      appId: '1:415922539355:android:4459e7544de5564cb5a87e',
      messagingSenderId: '415922539355',
      projectId: 'mahallada-app',
      storageBucket: 'mahallada-app.firebasestorage.app');
}
